version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    expose:
      - 3000 # Expose port 3000 within the network, can't be accessed by localhost:3000
    command: ['npm', 'run', 'start']

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - $NGINX_PORT:80
      - 443:443
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf # Overwrite default NGINX configuration
    environment: # Make sure NGINX runs on port 80
      - NGINX_HOST=$NGINX_HOST
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./public:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email $EMAIL --agree-tos --no-eff-email --staging -d $NGINX_HOST  -d www.$NGINX_HOST


#Named volumes can be used to save configuration to persistence
volumes:
  certbot-etc:
  certbot-var:


