version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    expose:
      - 3000
    command: ['npm', 'run', 'start']

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - $NGINX_PORT:80
      - 443:443
    volumes:
      - ./public:/var/www/html
      - ./nginx.template:/etc/nginx/conf.d/nginx.template # Overwrite default NGINX configuration
    environment: # Pass NGINX_HOST to NGINX config
      - NGINX_HOST=$NGINX_HOST
    depends_on:
      - app
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"


