version: '3'

services:
  webserver:
    volumes:
      - certbot-etc:/etc/letsencrypt/

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./public:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email $EMAIL --agree-tos --no-eff-email --staging -d $NGINX_HOST -d www.$NGINX_HOST


#Named volumes are used to save configuration to persistence
volumes:
  certbot-etc:
  certbot-var:


